# Generated by Django 4.2.1 on 2023-07-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevatorApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevatorrequest',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
