# Generated by Django 4.2.3 on 2023-07-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevatorApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevatorrequest',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
